# Translations template for invenio-records-resources.
# Copyright (C) 2025 CERN
# This file is distributed under the same license as the
# invenio-records-resources project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2025.
# 
# Translators:
# Júlia Babos, 2025
# Andrea Dömötör, 2025
# Zoltán Kanász-Nagy, 2025
# 
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: invenio-records-resources 5.10.1\n"
"Report-Msgid-Bugs-To: info@inveniosoftware.org\n"
"POT-Creation-Date: 2025-04-01 13:38+0000\n"
"PO-Revision-Date: 2024-03-21 15:18+0000\n"
"Last-Translator: Zoltán Kanász-Nagy, 2025\n"
"Language-Team: Hungarian (https://app.transifex.com/inveniosoftware/teams/23537/hu/)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.17.0\n"
"Language: hu\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

#: invenio_records_resources/records/systemfields/entity_reference.py:46
#, python-format
msgid "Invalid reference for '%(key)s': %(obj)s"
msgstr "Érvénytelen hivatkozás a(z) '%(key)s' kulcshoz: %(obj)s"

#: invenio_records_resources/resources/errors.py:61
#: invenio_records_resources/resources/errors.py:62
msgid "Invalid query string syntax."
msgstr "Érvénytelen szintaxis a lekérdezésben."

#: invenio_records_resources/resources/errors.py:63
msgid "Misconfigured search."
msgstr "Rosszul beállított keresés."

#: invenio_records_resources/resources/errors.py:74
msgid "Internal server error"
msgstr "Belső szerverhiba"

#: invenio_records_resources/resources/errors.py:120
msgid "Invalid querystring parameters."
msgstr "Érvénytelen lekérdezési paraméterek."

#: invenio_records_resources/resources/errors.py:126
#: invenio_records_resources/resources/errors.py:132
#: invenio_records_resources/services/errors.py:36
msgid "Permission denied."
msgstr "Engedély megtagadva."

#: invenio_records_resources/resources/errors.py:138
msgid "The record has been deleted."
msgstr "A rekord törölve lett."

#: invenio_records_resources/resources/errors.py:144
msgid "The persistent identifier is already registered."
msgstr "Az állandó azonosítót már regisztrálták."

#: invenio_records_resources/resources/errors.py:150
msgid "The persistent identifier does not exist."
msgstr "Az állandó azonosító nem létezik."

#: invenio_records_resources/resources/errors.py:156
msgid "The persistent identifier is not registered."
msgstr "Az állandó azonosító nincs regisztrálva."

#: invenio_records_resources/resources/errors.py:163
msgid "Not found."
msgstr "Nem található."

#: invenio_records_resources/resources/errors.py:170
#, python-format
msgid "Facet %(vocabulary_id)s not found."
msgstr "Facetta: %(vocabulary_id)snem található."

#: invenio_records_resources/resources/errors.py:183
msgid "Unable to decode JSON data in request body."
msgstr "Nem sikerült dekódolni a kérés JSON adatait."

#: invenio_records_resources/resources/errors.py:189
#: invenio_records_resources/resources/errors.py:195
msgid "Not a valid value."
msgstr "Érvénytelen érték"

#: invenio_records_resources/resources/errors.py:204
msgid "The file upload transfer failed, please try again."
msgstr "Sikertelen fájlfeltöltés, kérjük próbálja újból."

#: invenio_records_resources/resources/errors.py:211
msgid ""
"Uploading selected files will result in exceeding the max amount per record."
msgstr ""
"A kiválasztott fájlok feltöltésével meghaladná a rekordonkénti maximális "
"fájlmennyiséget."

#: invenio_records_resources/services/errors.py:51
#, python-format
msgid ""
"Revision id provided(%(expected_revision_id)s) doesn't match record's "
"one(%(record_revision_id)s)"
msgstr ""
"A megadott revízióazonosító (%(expected_revision_id)s) nem egyezik meg a "
"rekord aktuális azonosítójával (%(record_revision_id)s)"

#: invenio_records_resources/services/errors.py:73
#, python-format
msgid "Facet %(vocab)s not found."
msgstr "Facetta: %(vocab)s nem található."

#: invenio_records_resources/services/errors.py:83
#, python-format
msgid "Record '%(recid)s' has no file '%(file_key)s'."
msgstr "A(z) %(recid)s rekord(ok)ban nem található %(file_key)s nevű fájl. "

#: invenio_records_resources/services/errors.py:99
#, python-format
msgid "Record '%(recid)s' failed to upload file '%(file_key)s'."
msgstr ""
"Nem sikerült feltölteni a(z) %(file_key)s fájlt a(z) %(recid)s rekordhoz."

#: invenio_records_resources/services/errors.py:116
#, python-brace-format
msgid ""
"Uploading the selected files would result in {files_count} files (max is "
"{max_files})."
msgstr ""
"A kiválasztott fájlok feltöltése összesen {files_count} fájlt eredményezne "
"(a megengedett maximum: {max_files})."

#: invenio_records_resources/services/custom_fields/errors.py:37
#, python-format
msgid ""
"Namespace %(given_namespace)s is not valid for custom field %(field_name)s."
msgstr ""
"A %(given_namespace)s névtér nem érvényes a(z) %(field_name)segyéni "
"mező(k)höz."

#: invenio_records_resources/services/custom_fields/errors.py:54
#, python-format
msgid "Custom fields %(field_names)s are not configured."
msgstr "A(z) %(field_names)s egyéni mezők nincsenek beállítva."

#: invenio_records_resources/services/custom_fields/errors.py:70
#, python-format
msgid "Invalid argument %(arg_name)s passed when initializing custom field."
msgstr ""
"Érvénytelen paraméter %(arg_name)s került megadásra az egyéni mező "
"inicializálásakor."

#: invenio_records_resources/services/files/service.py:264
msgid "File upload transfer failed."
msgstr "Sikertelen fájlfeltöltés."

#: invenio_records_resources/services/files/transfer.py:77
msgid "File size limit exceeded."
msgstr "Túllépte a fájlméret limitet."

#: invenio_records_resources/services/files/transfer.py:103
msgid "Empty files are not accepted."
msgstr "Az üres fájlok nem lesznek elfogadva."

#: invenio_records_resources/services/records/config.py:36
msgid "Best match"
msgstr "Legjobb találat"

#: invenio_records_resources/services/records/config.py:40
msgid "Newest"
msgstr "Legújabb"

#: invenio_records_resources/services/records/config.py:44
msgid "Oldest"
msgstr "Legrégebbi"

#: invenio_records_resources/services/records/components/files.py:89
msgid "You must first delete all files to set the record to be metadata-only."
msgstr ""
"A csak-metaadat rekordra való átállításhoz először törölnie kell a fájlokat."

#: invenio_records_resources/services/records/params/pagination.py:39
msgid "Invalid pagination parameters."
msgstr "Érvénytelen lapozási paraméterek."

#: invenio_records_resources/services/records/params/querystr.py:31
msgid "You cannot specify both 'q' and 'suggest' parameters at the same time."
msgstr "Nem lehet egyszerre 'q' és 'suggest' paramétereket megadni."

#: invenio_records_resources/services/records/params/querystr.py:42
msgid "Invalid 'suggest' parameter."
msgstr "Érvénytelen 'suggest' paraméter."

#: invenio_records_resources/services/records/params/sort.py:62
#, python-format
msgid "Invalid sort option '%(sort_option)s'."
msgstr "Érvénytelen rendezési szempont: %(sort_option)s"

#: invenio_records_resources/services/records/queryparser/transformer.py:67
#, python-format
msgid "Invalid search field: %(field_name)s."
msgstr "Érvénytelen keresési mező: %(field_name)s"
